language: node_js

node_js:
  - "10"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- npm install -g @11ty/eleventy

install:
- npm install

before_script:
- git config --global user.name llighter
- git config --global user.email hadbsgkgmail.com

script:
- npm run build # eleventy & gulp & webpack build

# Deployment
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${__GITHUB_TOKEN__}
  keep_history: true
  repo: llighter/llighter.github.io
  local_dir: docs/
  target_branch: master