language: node_js

node_js:
  - "10"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- npm install -g @11ty/eleventy

install:
- npm install

before_script:
- git config --global user.name llighter
- git config --global user.email hadbsgkgmail.com
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
- npm run build # webpack build
- npx eleventy  # eleventy build

# Deployment
# 주의: <YOUR NAME>, <COMMIT MESSAGE>와 <YOUR EMAIL>를 변경해야합니다.
deploy:
  type: git
  repo: https://__GITHUB_TOKEN__@github.com/llighter/llighter.github.io
  branch: master
  local_dir: docs/
  message: "deploy..."